### ISSUE TITLE
What about new release?

### ISSUE THREAD

**Issue by nazar-pc** [themasch/node-bencode#79]
I'm particularly interested in `ArrayBufferView`/`TypedArray` support

**Comment by themasch** [comment]
So since there should be no API change that happens since 1.0, I'd suggest we go for 1.0.1 here? 
@jhermsmeier?

**Comment by nazar-pc** [comment]
I saw older versions of Node.js are no longer supported, so it should be worth more than a patch version.

**Comment by themasch** [comment]
Oh you are totally right. We should have done that with 1.0. So I guess 2.0 it is?

**Comment by nazar-pc** [comment]
2.0 would be better, just mention in changelog that nothing besides supported Node.js versions have changed incompatibly, so people can upgrade easily.

**Comment by jhermsmeier** [comment]
Agree, 2.0.0 would be good since even the typed array support was never published and that also changes behavior very significantly – for example, iirc WebTorrent was working around lack of typed array support in particular by being careful about what they pass to bencode, and this could certainly break things if bumped with a minor I imagine.

**Comment by themasch** [comment]
Created #81 for this.

**Comment by themasch** [comment]
just released 2.0 on npm. I hope this went all well, has been a long time since my last npm publish :D
